### ISSUE TITLE
Reading files from the web

### ISSUE THREAD

**Issue by gustavobio** [ropensci/finch#13]
Hi,

Links to DWC-A files shared with the integrated publishing toolkit usually look like this:

http://ipt.jbrj.gov.br/jbrj/archive.do?r=redlist_2013_taxons&v=3.12

However, dwca_read() uses the provided url to get the name of the file where the data will be stored:

basename("http://ipt.jbrj.gov.br/jbrj/archive.do?r=redlist_2013_taxons&v=3.12")

> basename("http://ipt.jbrj.gov.br/jbrj/archive.do?r=redlist_2013_taxons&v=3.12")
> [1] "archive.do?r=redlist_2013_taxons&v=3.12"

This doesn't work well as R can't find the path to the zip file later on:

> Error in unzip(writepath, exdir = dirpath) : 
>   cannot open file '/Users/gustavo/archive.do?r=lista_especies_flora_brasil&v=393.71/resourcerelationship.txt': Not a directory

I guess this could be solved by changing the basename to something else when the url isn't a direct link to a zip file.

Thanks!

**Comment by sckott** [comment]
thanks @gustavobio !

Right, we should go with something more robust. Perhaps even just use `tempfile()`

**Comment by sckott** [comment]
@gustavobio reinstall, should work now
