### ISSUE TITLE
Write path

### ISSUE THREAD

**Issue by gustavobio** [ropensci/finch#14]
Hi again,

I noticed that when using finch to download a bunch of DWC-A files my Sys.getenv("HOME") would get cluttered with them. It seems to me that the best places to write those files to would be either tempdir() or the working path if persistency is desired.

Thanks,

Gustavo.

**Comment by sckott** [comment]
thanks @gustavobio - I think we should go with `rappdirs` pkg for determining paths, sound good?

**Comment by gustavobio** [comment]
Yep, thanks!

**Comment by sckott** [comment]
@gustavobio reinstall and try again, should work now, just using caching with rappdirs on url inputs since file inputs should already be on disk, and fxn fail if not

**Comment by gustavobio** [comment]
Thank you!
