### ISSUE TITLE
... not actually being passed on to fread in dwca_read

### ISSUE THREAD

**Issue by gustavobio** [ropensci/finch#18]
Hi!

`...` arguments are not being passed on to `fread` in `dwca_read`. I've fixed this in my local repo, but it's probably easier for you to do it yourself here. Accents in some files aren't displayed correctly unless I pass `encoding = UTF-8` in `dwca_read`. 

Thanks!

**Comment by sckott** [comment]
thanks @gustavobio !  

will fix

**Comment by gustavobio** [comment]
Thanks, I've created a pull request to fix this #19

**Comment by sckott** [comment]
fixed in #19
