### ISSUE TITLE
issue with installing the finch

### ISSUE THREAD

**Issue by haniehsaeedi** [ropensci/finch#28]
I tried to install the package bt I ran into some difficulties, this is the error I get, I think it might have something to do with my R version?
> install.packages("finch")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/hanie/OneDrive/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/finch_0.4.0.zip'
Content type 'application/zip' length 302409 bytes (295 KB)
downloaded 295 KB

Also tried
> install_github("ropensci/finch")
Error in install_github("ropensci/finch") : 
  could not find function "install_github"
Can you help please?

**Comment by sckott** [comment]
`install_github` function is the `remotes` package, which you can install like `install.packages("remotes")`

To install Rtools see https://cran.r-project.org/bin/windows/Rtools/

**Comment by maelle** [comment]
This package is going to be archived.
