### ISSUE TITLE
Any possibility of more detailed output from dwca_validate()?

### ISSUE THREAD

**Issue by joelnitta** [ropensci/finch#29]
I am looking into validating Darwin Core "taxon" class data in R, and want to make sure I don't reinvent the wheel. I see {finch} has a [validator function](https://www.rdocumentation.org/packages/finch/versions/0.4.0/topics/dwca_validate), but it apparently just passes the zip off to https://tools.gbif.org/dwca-validator/ then returns only some very basic statistics (number of records) and a URL to the gbif dwca validator results, where all the juicy info is. 

It would be great if the validation results were actually output as a list or (even better) dataframe.

Do the developers of finch have any plans for this sort of functionality or know of any other existing packages that do such a thing? Thanks!

**Comment by sckott** [comment]
hi @joelnitta I've moved on to another job and no longer work on this package. If you want to take over maintenance let me know. You could also just fork the pkg, modify the code to do what you need.

**Comment by joelnitta** [comment]
I see, thanks for the clarification. I think my project (handling Darwin Core Taxon data in dataframes) is significantly distinct from {finch} (importing xml data into lists) that it makes sense for me to develop it as [a separate package](https://github.com/joelnitta/dwctaxon).

BTW are you still maintaining taxize?

**Comment by sckott** [comment]
Makes sense to me! 

No, not maintaining taxize anymore. Eduard Szoecs has taken over. A v1 has been in the works for a while, definitely some breaking changes, for the better though

**Comment by joelnitta** [comment]
Great to hear you still have somebody at the helm, and thanks for all of your work on taxize thus far! Lots of people depend on it. Looking forward to v1.

**Comment by sckott** [comment]
so glad you find it useful!

**Comment by maelle** [comment]
This package is going to be archived.
