### ISSUE TITLE
Create darwin core archives

### ISSUE THREAD

**Issue by sckott** [ropensci/finch#8]

**Comment by sckott** [comment]
probably will wait until `xml2` has write capability and those features on CRAN

**Comment by Daphnisd** [comment]
Is this still planned?

**Comment by sckott** [comment]
maybe. i haven't looked into what this would take per se, but yes, `xml2` does have write capability now, so is doable

**Comment by SteveViss** [comment]
Hi @sckott , I would like to convert extensive and newly opened datasets in Québec to DarwinCore Archive. I could always use the GBIF IPT to generate the DwC-A, but I'm not a GUI guy and I would like to regenerate the archive when datasets are updated... I think `finch` package will be more appropriate. I would like to help you with the development and focus on the simple version of the DwC. I have the idea of simply extend the EML structure ([see](https://github.com/ropensci/EML/blob/master/vignettes/creating-EML.Rmd), in EML package ) by adding a new field at the `dataTable`:

- dataTable
  - entityName
  - entityDescription
  - **DwCTerm**
  - physical
  - attributeList

The DC terms will be extracted from higher levels (`dataset` in EML) and then we have to validate each `DwCTerm` (within the DwC namespace) and control eventually for the taxonomy with `taxize`. What do you think?

**Comment by sckott** [comment]
@SteveViss Sounds great to me. Let me know if you have any questions.  We can refine it further if you can submit a pull request

**Comment by sckott** [comment]
need to submit a new version to CRAN, moving this to next milestone

**Comment by sckott** [comment]
@SteveViss still interested in doing this?
