### ISSUE TITLE
dwca_read() returns blank occurrence.txt data.frame despite this file not being blank

### ISSUE THREAD

**Issue by dmcglinn** [ropensci/finch#9]
I setup a GBIF query for all records in the genus "Quercus". This file is fairly large and that may be part of the problem. I ran the function `dwca_read` on a locally downloaded version of the file that I have linked to below. Also I did verify that the examples included in the help file of `dwca_read` worked, and with those datasets I was able to load the `occurrence.txt` data.frame

```
library(finch)

file <- "http://api.gbif.org/v1/occurrence/download/request/0020631-151016162008034.zip"
out <- dwca_read(file, read = TRUE)
#Read 0.0% of 1027888 rowss
out$data$occurrence.txt
#data frame with 0 columns and 0 rows
```

**Comment by sckott** [comment]
thanks for the report @dmcglinn 

I'll have a look

**Comment by sckott** [comment]
@dmcglinn looks like there's issues with `data.table::fread`, might switch to `readr` ....

**Comment by dmcglinn** [comment]
Thanks for taking a look @sckott. One quick thing I tried was 

```
library(readr)
dat = read_delim(file, delim='\t')
# Warning: 427550 parsing failures.
#  row        col   expected                       actual
#53671 identifier an integer urn:catalog:MAK:ISP:255683  
#53672 identifier an integer urn:catalog:MAK:ISP:209590  
#53673 identifier an integer urn:catalog:RYU:ISP:15230   
#53674 identifier an integer urn:catalog:HYO:VP:C1-151902
#53675 identifier an integer urn:catalog:HYO:VP:C1-151899
#..... .......... .......... ............................
#.See problems(...) for more details.
```

Some further checks suggest that about 10% of the data was not imported due to errors. 

In these cases it appears that the colons are causing a problem for import.

**Comment by sckott** [comment]
thanks Dan. I am also getting errors testing with `readr` - will have a look soon

**Comment by sckott** [comment]
@dmcglinn  making some progress, there's a dev version of `data.table` that does seem to work for the very large `occurrence.txt` file in your example, but not for the verbatim file, looking into why that doesn't work

**Comment by sckott** [comment]
@dmcglinn give it another try, after reinstalling from here `devtools::install_github("ropensci/finch")`, uses dev version of `data.table` that does work better, but still seems to fail sometimes.

**Comment by sckott** [comment]
@dmcglinn the pkg is now reading that file just fine, though it does take a while since it's so large. 

closing, but can reopen if still not fixed
